### ISSUE TITLE
problem reading EDF+

### ISSUE THREAD

**Issue by vlitvak** [fieldtrip/fieldtrip#1167] opened 2019-07-03 14:48 UTC
Hi, 

I got the following from an SPM user:

d like to use spm_eeg_convert to convert EDF+ format EEG data to SPM format but haven’t been able to get it to read the event data. I have confirmed events are included in the original EDF+ data using an EDF browser.

 

Initially I used spm_eeg_convert (v6244) and the data converted into SPM12 format fine – just no event data.

 

So I upgraded to the latest version of SPM12 (spm_eeg_convert (v7451)) to see if that would help but now get the following error message:

 

**********************

Error using ft_scalingfactor (line 178)

Error: Expression or statement is incomplete or incorrect.

 

Error in ft_read_data (line 1505)

  scaling = cellfun(@ft_scalingfactor, hdr.chanunit(chanindx(:)), chanunit(:));

 

Error in spm_eeg_convert (line 427)

            dat = ft_read_data(S.dataset,'header',  hdr, 'begsample', trl(i, 1),

            'endsample', trl(i, 2),...

 

*************************

 

The ft_scalingfactor function uses two arguments (‘old and ‘new’) and when this error occurs ‘old’  = [] and ‘new’ = ‘unknown’.

The problem comes down to trying to evaluate the statement:

'oldunit = ;'

Somewhere in the code there should be a check for empty units, but I'm not sure where you want to put it.

Vladimir

**Comment by robertoostenveld** [comment] 2019-07-04 10:42
taking the EDF files from https://www.teuniz.net/edf_bdf_testfiles/ (but not the bdf file) I don't get any explicit errors.

```
filename = {
  'ma0844az_1-1+.edf'
  'test_generator.edf'
  %   'test_generator_2.bdf' % channels with different sampling rate not supported
  'test_generator_2.edf'
  };

for i=1:numel(filename)
  hdr = ft_read_header(filename{i});
  dat = ft_read_data(filename{i});
  evt = ft_read_event(filename{i});
end
```

the `Error: Expression or statement is incomplete or incorrect.` would be a syntax error, possibly a missing bracket or so in the FT code. That seems to be fixed, so please update to the latest release of fieldtrip (note the change in release management, see http://www.fieldtriptoolbox.org/development/dashboard/, all releases from the release branch now pass all tests, master is the same as it used to be).

I cannot reproduce your error with ft_chanunit, but [] would be an invalid input (and should be solved before it enters the function).

If I do `edf2fieldtrip('ma0844az_1-1+.edf')` all data is read according to my expectations, but annotations are not parsed (also as expected). 

Can you share the problematic file?

**Comment by robertoostenveld** [comment] 2019-07-04 10:49
the parsing of the EDF+ annotation channel happens here https://github.com/fieldtrip/fieldtrip/blob/f99a322b0f81bbe3c9f6bf1603addcd38e71696e/fileio/ft_read_event.m#L626

**Comment by robertoostenveld** [comment] 2019-07-04 10:56
testing it on the `ma0844az_1-1+.edf` example file, I see that detectflank=up by default in ft_read_event, which causes the annotations to be skipped. It would actually be fine to read both a regularly-sampled trigger channel and also the annotations.  I'll update the code.

**Comment by robertoostenveld** [comment] 2019-07-04 11:04
regretfully, the `ma0844az_1-1+.edf`example file does not have a valid annotation channel... or the parsing is incorrect. I don't think I can be of further assistance at the moment.

**Comment by vlitvak** [comment] 2019-07-04 11:10
I'll ask for the example file

**Comment by vlitvak** [comment] 2019-07-08 15:48
Here is the example file. I do get the error with my SPM which has FT from at most a month ago.

https://drive.google.com/open?id=1FdFM5VVqI3_fUdXYGsj94OfijsgzVqx4

The command that causes the error is

ft_read_data('ARH2019.06.28_10.41.34.EDF', 'begsample', 1, 'endsample', 2, 'chanunit', repmat({'uV'}, 1, 71))

**Comment by schoffelen** [comment] 2020-03-18 09:08
Hi @vlitvak I am using the opportunity to clean up loose ends a bit. Is this still an issue? I tried to download the example file myself, but the link is broken.

**Comment by robertoostenveld** [comment] 2020-03-18 09:56
Hi @schoffelen, thanks for picking this up. I found a `test_issue1167.m` file on my computer which contains   

```
filename = {
  'ma0844az_1-1+.edf'
  'test_generator.edf'
  %   'test_generator_2.bdf' % channels with different sampling rate not supported
  'test_generator_2.edf'
  };

for i=1:numel(filename)
  % this will read only the channels with the highest sampling rate
  hdr = ft_read_header(filename{i});
  dat = ft_read_data(filename{i});
  evt = ft_read_event(filename{i});
  
  % this will read all channels, upsample, and append
  data = edf2fieldtrip(filename{i});
end
```

But I have not been able to find the data files that it refers to. The file test_generator_2.edf appears to be used in MNE-Python testing (I found a reference to it in a py file) and hence might be available online.

**Comment by schoffelen** [comment] 2020-03-19 08:06
OK, I found the test data online, I will add them to the test data directory /home/common/matlab/fieldtrip/data/test/original/eeg/edf

@robertoostenveld shall I copy-paste the code snippet above in my own version of test_issue1167.m, or could you perhaps copy it en-block here. 

My suggestion is to implement the test function, hope that it works, and close the issue.

PS: there's also a test .bdf file, shall I copy that one into the bdf folder?

**Comment by robertoostenveld** [comment] 2020-03-19 08:49
It would be fine to add the BDF test files, but the problem probably has nothing to do with BDF. 

There is no such thing as BDF+ and the way events are coded in a BDF file is usually as a continuously sampled trigger/TTL channel, whereas EDF+ introduces annotations  (over EDF itself, which only has continuously sampled trigger/TTL channels or analog channels). 

Btw, my `test_issue1167.m does not contain anything more of relevance than the lines I already pasted above. Not even a function declaration or a walltime/mem specification. So clearly an incomplete test snippet.

**Comment by schoffelen** [comment] 2020-03-19 08:50
OK, then I will create one from scratch to get this finished.

**Comment by robertoostenveld** [comment] 2020-03-19 08:51
for reference and to let @vlitvak know what is available, we have the following test files now:

```
roboos@mentat002> pwd
/home/common/matlab/fieldtrip/data/test/original/eeg/edf
roboos@mentat002> ls -al
total 159088
drwxrwsr-x  2 roboos fieldtrip     4096 Mar 19 09:25 .
drwxrwsr-x 11 roboos fieldtrip     4096 Jul  1  2019 ..
-rw-rw-r--  1 roboos fieldtrip 77032192 Apr 11  2011 0601_s.edf
-rw-r--r--  1 jansch fieldtrip 27826914 Mar 19 09:25 ma0844az_1-1+.edf
-rw--w----  1 roboos fieldtrip  9163328 Jul  1  2019 RecordSession_2017.09.07_20.41.53.edf
-rw-rw-r--  1 roboos fieldtrip 41304240 Oct 17  2015 shhs1-200001.edf
-rw-r--r--  1 jansch fieldtrip  2704528 Mar 19 09:25 test_generator_2.edf
-rw-r--r--  1 jansch fieldtrip  4189352 Mar 19 09:25 test_generator.edf
```

**Comment by schoffelen** [comment] 2020-03-25 09:07
relevant test data seems lost to follow up. Until it's found again, this can't be fixed.

**Closed by schoffelen** 2020-03-25 09:07 UTC
Labels: unconfirmed
