### ISSUE TITLE
implement a minimal test_ft_xxx script for all “main” fieldtrip functions

### ISSUE THREAD

**Issue by malinINCF** [fieldtrip/fieldtrip#1802] opened 2021-06-23 10:21 UTC
a. Make a list of functions that do and do not have a test script
b. Group the functions according to their input data and document this. 
c. For each group, implement a test script

**Comment by robertoostenveld** [comment] 2021-06-28 07:42
using the following command-line code I identified the list of functions:

```
cd fieldtrip
for file in ft_*.m ; do if [ -n test/test_$file ] ; then echo test_$file ; fi; done
```

test_ft_analysispipeline.m
test_ft_annotate.m
test_ft_anonymizedata.m
test_ft_appenddata.m
test_ft_appendfreq.m
test_ft_appendlayout.m
test_ft_appendsens.m
test_ft_appendsource.m
test_ft_appendspike.m
test_ft_appendtimelock.m
test_ft_artifact_clip.m
test_ft_artifact_ecg.m
test_ft_artifact_eog.m
test_ft_artifact_jump.m
test_ft_artifact_muscle.m
test_ft_artifact_nan.m
test_ft_artifact_threshold.m
test_ft_artifact_tms.m
test_ft_artifact_zvalue.m
test_ft_audiovideobrowser.m
test_ft_badchannel.m
test_ft_badsegment.m
test_ft_channelnormalise.m
test_ft_channelrepair.m
test_ft_clusterplot.m
test_ft_combineplanar.m
test_ft_componentanalysis.m
test_ft_conjunctionanalysis.m
test_ft_connectivityanalysis.m
test_ft_connectivityplot.m
test_ft_connectivitysimulation.m
test_ft_crossfrequencyanalysis.m
test_ft_databrowser.m
test_ft_defacemesh.m
test_ft_defacevolume.m
test_ft_defaults.m
test_ft_definetrial.m
test_ft_denoise_dssp.m
test_ft_denoise_pca.m
test_ft_denoise_prewhiten.m
test_ft_denoise_synthetic.m
test_ft_denoise_tsr.m
test_ft_detect_movement.m
test_ft_dipolefitting.m
test_ft_dipolesimulation.m
test_ft_electrodeplacement.m
test_ft_electroderealign.m
test_ft_electrodermalactivity.m
test_ft_eventtiminganalysis.m
test_ft_examplefunction.m
test_ft_freqanalysis.m
test_ft_freqanalysis_mvar.m
test_ft_freqbaseline.m
test_ft_freqdescriptives.m
test_ft_freqgrandaverage.m
test_ft_freqinterpolate.m
test_ft_freqsimulation.m
test_ft_freqstatistics.m
test_ft_globalmeanfield.m
test_ft_headmovement.m
test_ft_heartrate.m
test_ft_interactiverealign.m
test_ft_interpolatenan.m
test_ft_lateralizedpotential.m
test_ft_layoutplot.m
test_ft_math.m
test_ft_megplanar.m
test_ft_megrealign.m
test_ft_meshrealign.m
test_ft_movieplotER.m
test_ft_movieplotTFR.m
test_ft_multiplotCC.m
test_ft_multiplotER.m
test_ft_multiplotTFR.m
test_ft_mvaranalysis.m
test_ft_neighbourplot.m
test_ft_networkanalysis.m
test_ft_prepare_headmodel.m
test_ft_prepare_layout.m
test_ft_prepare_leadfield.m
test_ft_prepare_mesh.m
test_ft_prepare_montage.m
test_ft_prepare_neighbours.m
test_ft_prepare_sourcemodel.m
test_ft_preprocessing.m
test_ft_qualitycheck.m
test_ft_recodeevent.m
test_ft_redefinetrial.m
test_ft_regressconfound.m
test_ft_rejectartifact.m
test_ft_rejectcomponent.m
test_ft_rejectvisual.m
test_ft_removetemplateartifact.m
test_ft_reproducescript.m
test_ft_resampledata.m
test_ft_respiration.m
test_ft_scalpcurrentdensity.m
test_ft_singleplotER.m
test_ft_singleplotTFR.m
test_ft_sliceinterp.m
test_ft_sourceanalysis.m
test_ft_sourcedescriptives.m
test_ft_sourcegrandaverage.m
test_ft_sourceinterpolate.m
test_ft_sourcemovie.m
test_ft_sourceparcellate.m
test_ft_sourceplot.m
test_ft_sourceplot_interactive.m
test_ft_sourcestatistics.m
test_ft_sourcewrite.m
test_ft_statistics_analytic.m
test_ft_statistics_crossvalidate.m
test_ft_statistics_montecarlo.m
test_ft_statistics_mvpa.m
test_ft_statistics_stats.m
test_ft_steadystatesimulation.m
test_ft_stratify.m
test_ft_timelockanalysis.m
test_ft_timelockbaseline.m
test_ft_timelockgrandaverage.m
test_ft_timelocksimulation.m
test_ft_timelockstatistics.m
test_ft_topoplotCC.m
test_ft_topoplotER.m
test_ft_topoplotIC.m
test_ft_topoplotTFR.m
test_ft_virtualchannel.m
test_ft_volumebiascorrect.m
test_ft_volumedownsample.m
test_ft_volumelookup.m
test_ft_volumenormalise.m
test_ft_volumerealign.m
test_ft_volumereslice.m
test_ft_volumesegment.m
test_ft_volumewrite.m
test_ft_wizard.m

That list comprises 136 items. Some of them are not needed (test_ft_wizard.m, test_ft_stratify.m, test_ft_analysispipeline.m, ...) since those don't map onto "regular" main functions with a FT data structure as input and output.

**Comment by robertoostenveld** [comment] 2021-06-28 07:44
I recommend that you organize them by input data type, and then do one type at a time, starting with those that expect raw data.  That allows you to reuse large parts of the test function. With a list of all files in a temporary file `list`, I see 

```
for file in `cat list` ; do grep -l ft_checkdata.*raw $file ; done  
````

ft_appenddata.m
ft_appendspike.m
ft_artifact_clip.m
ft_artifact_ecg.m
ft_artifact_nan.m
ft_artifact_threshold.m
ft_artifact_zvalue.m
ft_audiovideobrowser.m
ft_badchannel.m
ft_badsegment.m
ft_channelnormalise.m
ft_channelrepair.m
ft_combineplanar.m
ft_componentanalysis.m
ft_connectivityanalysis.m
ft_databrowser.m
ft_denoise_dssp.m
ft_denoise_pca.m
ft_denoise_prewhiten.m
ft_denoise_synthetic.m
ft_denoise_tsr.m
ft_detect_movement.m
ft_electrodermalactivity.m
ft_eventtiminganalysis.m
ft_examplefunction.m
ft_freqanalysis.m
ft_heartrate.m
ft_interpolatenan.m
ft_megplanar.m
ft_megrealign.m
ft_mvaranalysis.m
ft_prepare_montage.m
ft_preprocessing.m
ft_redefinetrial.m
ft_rejectartifact.m
ft_rejectcomponent.m
ft_rejectvisual.m
ft_removetemplateartifact.m
ft_resampledata.m
ft_respiration.m
ft_scalpcurrentdensity.m
ft_timelockanalysis.m
ft_virtualchannel.m

Again, here are some that don't make sense to start with (like ft_audiovideobrowser, or ft_appendspike, or ft_volumelookup). I would also postpone all plotting functions, or functions with a GUI.

**Comment by robertoostenveld** [comment] 2021-06-28 07:47
You can start with some dummy data, as done in https://github.com/fieldtrip/fieldtrip/blob/master/test/test_ft_appendfreq.m, and simply call the to-be-tested function with that as input. In first instance, you don't have to loop over all options, just do the simplest execution of the to-be-tested function with some input data and cfg.

**Comment by robertoostenveld** [comment] 2021-06-28 11:57
I realize that some functions will only work on MEG, others only on EEG, and some don't care. @schoffelen, do you think it would make sense to add some template grad structures for the various MEG systems to 'template/gradiometer'?

**Comment by schoffelen** [comment] 2021-06-28 12:06
I guess the purpose would be to have them externably accessible (as opposed to /home/common/..../sens)? I think that would make sense in general. I guess these would be in head coordinates?

**Comment by robertoostenveld** [comment] 2021-06-28 12:08
yes, so that we use them in test scripts that can run anywhere (e.g. using continuous integration on Travis/Azure). And head coordinates makes most sense, but ideally they would also be symmetric so that they can be used for serious simulations (like those of Maria-Carla).

**Comment by robertoostenveld** [comment] 2021-07-06 10:40
Although #1821 implements some, it does not implement all test scripts that are planned. So this issue should not be closed yet.

**Comment by robertoostenveld** [comment] 2021-07-08 06:53
Two batches of test scripts have now been merged with they master branch. There are still some test scripts to go, so this issue should not yet be closed.

**Closed** 2021-07-12 09:55 UTC
Labels: enhancement, summer project

**Comment by robertoostenveld** [comment] 2021-07-12 09:57
I think that with #1829 @LucaLaFisca has completed this deliverable. There are still a few functions that don't have a test script. That has been discussed and we agreed to not implement them in this project. Luca, could you document them here, so that we look them up in the future?
