### ISSUE TITLE
ft_prepare_headmodel bug when using fresh OpenMEEG install

### ISSUE THREAD

**Issue by jordannicolasalves** [fieldtrip/fieldtrip#1870] opened 2021-09-02 08:48 UTC
**Describe the bug**
Due to recent changes in the file creation and handling by OpenMEEG the current version of om_write_geom.m in the /fieldtrip/external/openmeeg folder writes wrong geometry file.

**To Reproduce**
ft_prepare_headmodel with a cfg.method= 'openmeeg'; with an updated or fresh install OpenMEEG

**Environment and versions**
 - Ubuntu 20.04.3 LTS
 - MATLAB R2020b
 - FieldTrip most recent master branch from github revision ea9008617
 - om_assemble version 2.4.9999 compiled on Jul  6 2021

**Additional context**
Worked on a fix that I would be happy to contribute

**Comment by schoffelen** [comment] 2021-09-02 09:04
what does 'wrong' mean? A bit more context would be much appreciated (at least in order to document what's going wrong), and of course a fix would be great.

**Comment by robertoostenveld** [comment] 2021-09-02 09:25
@jordannicolasalves perhaps you can try to follow https://github.com/fieldtrip/fieldtrip/blob/master/test/test_headmodel_openmeeg.m and run through that script so that we have something to exactly reproduce the problem. You won't be able to exactly follow `test_headmodel_openmeeg.m` as it is implemented to run on our compute cluster (which it does [every night without any errors](https://www.fieldtriptoolbox.org/development/testing/)), but with some small changes you should be able to go through the script

**Comment by jordannicolasalves** [comment] 2021-09-02 09:26
Sorry for lack of precisions.

OpenMEEG introduced new conventions for writing .geom files and is stated in the tutorial for meshes generation (see on attached .png file from OpenMEEG website)

https://openmeeg.github.io/tutorial.html#fig-geom
![geom_openmeeg](https://user-images.githubusercontent.com/40459486/131817886-762d5038-5da0-468b-81a2-b2d3d5790041.png)

When using current version of om_write_geom provided with fieldtrip in the /external/openmeeg folder,  the .geom file generated still follows previous conventions and is hence unreadable by following steps.
Fix can be linked as .m file or can be committed through github.

**Comment by schoffelen** [comment] 2021-09-02 09:29
So, to paraphrase, there's a potential backward compatibility issue, with an interaction between the version of openmeeg that is used outside fieldtrip, and the stuff that fieldtrip uses. Had you used an older version of openmeeg this wouldn't have occurred right?

Just updating the m-file in fieldtrip is not going to fix it, because if somebody uses an older version of openmeeg I suspect we get the problem the other way around.

**Comment by jordannicolasalves** [comment] 2021-09-02 09:36
Since I recently installed a fresh OpenMEEG and I am the first one to encounter the problem within my research group (that have been using the scripts before, presumably on older OpenMEEG installs), it could very well be a backward compatibility issue.

**Comment by sarangnemo** [comment] 2022-03-16 14:34
Seems we lost track of this. Anyway, to clarify what's happened with OpenMEEG – they introduced a new convention for formatting their _.geom_ head model configuration file several years ago, "Domain Description 1.1" (circa 2015 if memory serves), deprecating the original convention that the FieldTrip pipeline has been using, "Domain Description 1.0". However, the deprecated convention (1.0) still worked until they finally disabled it more recently, likely in versions since summer 2021. Therefore, current versions of OpenMEEG reject the _.geom_ file provided by the current FieldTrip pipeline.

As @jordannicolasalves has done, updating the FieldTrip pipeline to instead use the current _Domain Description 1.1_ resolves the problem, while remaining compatible with the last several years of OpenMEEG installations. This should therefore give identical results and not break functionality for anybody still using older OpenMEEG versions. Perhaps @papadop or @agramfort can confirm this.

**Comment by papadop** [comment] 2022-03-16 17:25
I have no remembering of removing
      the old file format (and normally that would be me that would have
      done that at least since 2019).
    I quickly went through the Changelogs
      of 2020 and 2021 and found nothing related to that (but it was
      quick, so I may have missed
      it or it could have been done earlier). And I can confirm the code
      is still there. However, I did some code reorganization and may 
      have caused some problems in doind that....
    
    
    
    So I suspect I may have introduced a
      bug in the handling of the old file format. If you have a
      self-contained example (and the version
      of the affected OpenMEEG), I will have a look and correct the bug.
      
    
    
    
    That being said, it is clearly better
      to use the 1.1 file format as one day or an another the
      support for the old file format will be suppressed (all the more
      if there are bugs depending on the ease of their correction). I do
      not remember if the support
      of the old file format involves a lot of code, but clearly it is
      much less tested nowadays than it was and the new file format is a
      strict generalization of the
    old, so no functionality is lost. It is
      a little bit more complicated but allows for non-nested geometries
      (which indeed remains a rare type of model in practise,
      but again changes are not that big to go from format 1.0 to format
      1.1.
    
    
    I will look to see if I can provide a
      conversion script that would help the transition....
    
    
        Theo.
    
    
    
    On 3/16/22 15:35, Sarang S. Dalal
      wrote:
    
    
      
      Seems we lost track of this. Anyway, to clarify
        what's happened with OpenMEEG – they introduced a new convention
        for formatting their .geom head model configuration
        file several years ago, "Domain Description 1.1" (circa 2015 if
        memory serves), deprecating the original convention that the
        FieldTrip pipeline has been using, "Domain Description 1.0".
        However, the deprecated convention (1.0) still worked until they
        finally disabled it more recently, likely in versions since
        summer 2021. Therefore, current versions of OpenMEEG reject the
        .geom file provided by the current FieldTrip pipeline.
      As @jordannicolasalves has done,
        updating the FieldTrip pipeline to instead use the current Domain
          Description 1.1 resolves the problem, while remaining
        compatible with the last several years of OpenMEEG
        installations. This should therefore give identical results and
        not break functionality for anybody still using older OpenMEEG
        versions. Perhaps @papadop
        or @agramfort
        can confirm this.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/fieldtrip/fieldtrip/issues/1870#issuecomment-1069196876",
"url": "https://github.com/fieldtrip/fieldtrip/issues/1870#issuecomment-1069196876",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sarangnemo** [comment] 2022-03-16 18:06
Thanks @papadop. @jordannicolasalves and I already have the 1.1 format implemented in a revision of the FieldTrip pipeline, so no need to work on a conversion script. We'd like to simply commit it as a PR to FieldTrip at this point.

I can confirm that the 1.0 format (at least the way we had implemented it in FieldTrip) was working with my previous OpenMEEG installation from 2019, but that it no longer worked after updating with the latest Github version in Fall 2021. I can provide you with an example offline if you'd like to see what happened.

**Comment by sarangnemo** [comment] 2022-03-16 18:08
Maybe for now, @papadop, can you reassure us that the 1.1 format is indeed compatible for effectively all OpenMEEG versions that can be expected to still be in use in the wild?

**Comment by papadop** [comment] 2022-03-16 18:13
> I can provide you with an example offline if you'd like to see what happened.

Yes please...

**Comment by papadop** [comment] 2022-03-16 18:29
> Maybe for now, @papadop, can you reassure us that the 1.1 format is indeed compatible for effectively all OpenMEEG versions that can be expected to still be in use in the wild?

Well I do not control what versions are still in use in the wild !!!
As you said the new file format is there for quite some time now. The non-nested implementation (for which the 1.1 file format is required) has been committed in 2013. This new file format is mentioned in the tutorial for OpenMEEG 2.2 in 2013.

So it is already implemented for 9 years which for software is a long time.... I'd expect anyone to have updated its computer/system by that time, which may have required an upgrade of OpenMEEG. Then I cannot guarantee that this update was done if the earlier versions of OpenMEEG was still working on the newer computer/system. 

But yes the 1.1 file format is supported (and preferred) for quite many years.

**Comment by schoffelen** [comment] 2022-03-17 12:20
Thanks for picking up on this. We look forward to a PR.

**Closed** 2022-07-11 06:52 UTC
Labels: bug

**Comment by sarangnemo** [comment] 2022-07-11 07:50
Thanks for this @schoffelen! Sorry we've been silent over here, @jordannicolasalves is defending his thesis on Wednesday. :-) Your PR looks similar to what he had (privately) written, so it looks like it should work in our real pipelines too, especially if the test script works. I'll try it out in August.
AFAIK, the conductivity file format hasn't changed; the surface labels simply need to match with the _geom_ file.
