### ISSUE TITLE
Can't read a MAG4Health fif file

### ISSUE THREAD

**Issue by vlitvak** [fieldtrip/fieldtrip#2459] opened 2024-11-06 10:50 UTC
We got a fif file from the MAG4Health OPM system and it doesn't convert although is readable in Brainstorm and MNE.

https://liveuclac-my.sharepoint.com/:u:/g/personal/skaalit_ucl_ac_uk/EeYMnPp18XtMpArLrRW2hFkByVpiNLKTiduqxTTWbvxdWA?e=fSh1Xg

**Comment by schoffelen** [comment] 2024-11-06 11:03
this is due to a low level error in fiff_open. So to some extent this is out of our hands... 
It surprises me that MNE and brainstorm work, given that Matti's reading code so far has followed the official fif-specs, which suggests that Mag4Health produces fif-invalid fif files

**Comment by vlitvak** [comment] 2024-11-06 11:08
What code does Brainstorm use? Is there a way to submit this to Matti or someone else who maintains the fif reader?

**Comment by schoffelen** [comment] 2024-11-06 12:04
Well, let's first investigate a bit more. We need to be sure that it's not Mag4Health who is defining invalid files. (and that the other softwares just are a bit less strict in enforcing file format validity)

**Comment by schoffelen** [comment] 2024-11-06 12:12
The problem seems to be that the fif-reader tries to read beyond then end of the file, which causes the low-level error.

**Comment by schoffelen** [comment] 2024-11-06 12:16
The error is caused by the fact that in the file sent by you, the last tag in the file has a value of '0' for what in the code is referred to as ```tag.next```, whereas in a(n) (what I think to be properly formatted fif-file) other fif-file I just tried to read, the tag.next = -1, which causes the necessary exit out of the while-loop in fiff_open (at line 95-103)

**Comment by schoffelen** [comment] 2024-11-08 12:51
OK, this is now fixed with https://github.com/fieldtrip/fieldtrip/commit/a153aaf2bc1fee2d6855a2ec56c8aa2adf9e9976 
@vlitvak, we should perhaps nudge the MAG4Health people to update their acquisition software, so that at the end of the file a correct tag will be written. Would you do that?

**Comment by vlitvak** [comment] 2024-11-08 13:07
Yes, I've sent all the links to Caroline and she will forward to them hopefully.

**Closed** 2024-11-09 13:42 UTC
Labels: bug
