### ISSUE TITLE
Bug with linestyle cell array only plots last style in array

### ISSUE THREAD

**Issue by eurunuela** [fieldtrip/fieldtrip#928] opened 2019-01-15 13:12 UTC
I've found and solved this bug that makes plots only show the last linestyle in the cell array. I've edited 3 of the files to solve the bug but have no permission to push them to the repo. You can find the code here:

[correctedFunctions.zip](https://github.com/fieldtrip/fieldtrip/files/2759744/correctedFunctions.zip)

**Comment by schoffelen** [comment] 2019-09-11 10:45
suggestions for code fixes are always welcome. Indeed, you don't have push permission, but you can submit a pull request on github. Could you check whether in the current version of the code, the issue is still an issue, and if so, submit a pull request addressing it.
Otherwise, please close the issue

**Comment by schoffelen** [comment] 2020-03-18 08:54
Dear @eurunuela would it be possible to make your fixes into a PR? We can then merge it into the main repo?

**Comment by eurunuela** [comment] 2020-03-18 08:56
Sure! I’ll take care of it.

**Comment by schoffelen** [comment] 2020-03-18 08:57
And apologies for the delay. I guess that the current global situation allows me to clean up some loose ends... Take care!

**Comment by eurunuela** [comment] 2020-03-18 09:16
That’s alright! I had completely forgotten about this as I actually wrote the fix for a colleague of mine.

**Comment by eurunuela** [comment] 2020-03-18 10:21
Closing the issue as the bug was already fixed.

**Comment by schoffelen** [comment] 2020-03-20 08:16
This just came in on the discussion list:

I am trying to plot two ERPs in ft_multiplotER with different line styles. According to the documentation, I should be able to feed a cell array of styles into cfg.linestyle. But when I do that, it seems to only use the last style in the cell array. Here's an example of the code I'm using:

figure;
cfg = [];
cfg.parameter = 'avg';
cfg.layout = lay;
cfg.showlabels= 'yes';
cfg.linestyle = {'-' '--'};
cfg.channel = {'EEG' '-M1' '-M2'};
ft_multiplotER( cfg, MMNsonly.ka3, MMNsonly.pa3 );

I expected that this should make one of the ERPs be a solid line and one a dashed line, but it made both of them dashed lines, as you can see here: https://imgur.com/a/RybbkLq

I'm not sure if I'm missing something that I should be doing, or if this is a bug. If anyone needs to be able to reproduce this, let me know and I can try to Dropbox you my data and layout to allow you to run this code.

Thanks,
Steve

**Comment by schoffelen** [comment] 2020-03-20 08:28
OK, I still need to wake up, the first step of course would be for Steve to check his fieldtrip version, and try again with a more recent one.

**Comment by eurunuela** [comment] 2020-03-20 09:40
Indeed, that's the kind of bug I reported a year ago. As per discussions in #1349, this should have been fixed and the latest version in master should work properly. 

I'd definitely ask Steve what his version is, and to update to the newest if possible.

**Comment by schoffelen** [comment] 2020-03-20 09:41
Yes, thanks. Apologies for the 'panic soccer' as we would say in Dutch

**Closed by schoffelen** 2020-03-20 09:41 UTC
