### ISSUE TITLE
Issue with ft_chantype

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2090] opened 2022-08-10 22:58 UTC
https://drive.google.com/file/d/1DtuLMBD9kHpJPTso8Cm4mkf3C7-P3-t6/view?usp=sharing
Using the attached structure (output of ft_preprocessing)

```
ft_chantype(dat, 'eeg')
``` 

is empty. Yes, the dat.elec structure clearly contains channels of type EEG.

```
>> dat.elec

ans = 

  struct with fields:

     chanpos: [64×3 double]
    chantype: {64×1 cell}
    chanunit: {64×1 cell}
     elecpos: [64×3 double]
       label: {64×1 cell}
        type: 'eeg1010'
        unit: 'mm'

>> dat.elec.chantype

ans =

  64×1 cell array

    {'eeg'}
    {'eeg'}
    {'eeg'}
    {'eeg'}
    {'eeg'}
    {'eeg'}
    {'eeg'}
    {'eeg'}
    {'eeg'}
    {'eeg'}
```

**Comment by schoffelen** [comment] 2022-08-11 05:43
Hi @arnodelorme if I download the data (containing the variable data_clean) and do: ft_chantype(data_clean) I get a list with 79 entries (as expected).

Can you elaborate what the issue exactly?

**Comment by arnodelorme** [comment] 2022-08-15 17:24
Just redownloaded the data and tried ft_chantype.

```
ft_chantype(data_clean, 'eeg')

ans =

  79×1 logical array

   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   ...
```

**Comment by arnodelorme** [comment] 2022-08-15 17:25
This is Fieldtrip from August 8th (from Github). 
MacOS and MATLAB 2021b.

**Comment by schoffelen** [comment] 2022-08-15 18:03
what's the relation between what you call 'data_clean' in the previous comment, and the 'dat' variable that you provided earlier?

**Comment by schoffelen** [comment] 2022-08-15 18:23
Sorry, this one got closed by accident, because it was linked to another PR (which was irrelevant to the current issue).

**Comment by arnodelorme** [comment] 2022-08-15 20:32
"what's the relation between what you call 'data_clean' in the previous comment, and the 'dat' variable that you provided earlier?"

Yes, should have been data_clean not dat. I was just typing from memory. But I tried it again (see above).

**Comment by schoffelen** [comment] 2022-08-18 11:57
Yes, confirmed. Could it be a case sensitive thing? Probably...

If I do

ft_chantype(data_clean), I get a list with a lot of 'EEG' channels.

If I do

ft_chantype(data_clean.elec), I get a lot of 'eeg'.

**Comment by schoffelen** [comment] 2022-08-18 11:59
indeed, the data_clean.hdr.chantype has capitalized chantypes.

**Comment by schoffelen** [comment] 2022-08-18 12:06
I think I can add a change to ft_chantype:

if isfield(input, 'chantype')
  % start with the provided channel types
  chantype = input.chantype(:);

into 

  chantype = lower(input.chantype(:));

That would make it more robust in FT. Would that do for you @arnodelorme? (Still surprising to have a dataset with upper case chantypes though.

**Comment by schoffelen** [comment] 2022-08-18 12:07
Based on the above, the following would work as expected on the current data (with the current code)

ft_chantype(rmfield(data_clean, 'hdr'), 'eeg')

**Comment by schoffelen** [comment] 2022-09-15 13:23
I think that this one can be closed, @arnodelorme agrees? (I have silently pushed a change to the repo to ensure lower-cased chantypes )

**Closed by schoffelen** 2022-09-15 13:23 UTC
Labels: bug, unconfirmed
