### ISSUE TITLE
Parfor seems not supported due to preamble issues

### ISSUE THREAD

**Issue by stephenwhitmarsh** [fieldtrip/fieldtrip#1249] opened 2019-10-30 13:25 UTC
Using fieldtrip functions in a parfor loop seems to break due to preable issues. 
For example, try:

parpool(2)
parfor i = 1 : 2
   ft_version
end

This results in:

Error using ft_version (line 145)
Insufficient number of outputs from right hand side of equal sign to satisfy assignment.

This concerns lines 144-145 in ft_version:
  a = ver(ftpath);
  ftver = a.Version;

This is the last 'else' in a list. I tried to try/catch it, but that resulted in problem further down the line in my script, in this case with ft_preprocessing, but it is probably a more general issue:

---
Error using ft_preamble_init (line 50)
Output argument "ftver" (and maybe others) not assigned during call to "ft_version".

Error in ft_preamble (line 83)
evalin('caller', full_cmd);

Error in ft_preprocessing (line 182)
ft_preamble init

Error in writeSpykingCircus_parfor (line 32)
            parfor idir_parfor = 1:length(MuseStruct{ipart})

---

This problem occurs on a Linux kernel. I think the problem might be related to the fact that for every parallel job, all the functions/data are transferred to every 'worker', and somehow loose a real path, therefor not able to add paths with private functions. At least that's my very tentative guess.

**Comment by stephenwhitmarsh** [comment] 2019-12-10 08:32
@robertoostenveld Wasn't there a related problem during the PracticalMEEG worshop at ICM, Paris? Would the solution there (I passed it on to you, don't know how you fixed it) be relevant here?

**Comment by robertoostenveld** [comment] 2019-12-10 11:11
there was indeed some issue with ft_version during the paris workshop. Don't recall the details, I did not add it to my hands-on notes. But I think it had to do with a fieldtrip-lite version that was downloaded as part of EEGLAB.

**Comment by robertoostenveld** [comment] 2019-12-10 12:31
```
parpool local
parfor i=1:4
ft_version
end
```

> This is FieldTrip, revision fc7fe1ce8.
This is FieldTrip, revision fc7fe1ce8.
This is FieldTrip, revision fc7fe1ce8.
This is FieldTrip, revision fc7fe1ce8.

I cannot reproduce the problem. Can you provide more information under which conditions it happens?

**Comment by robertoostenveld** [comment] 2019-12-10 12:35
or perhaps better: can you run line 144 that determines the version and check whether the return structure contains the field `Version`?  
```
  a = ver(ftpath);
  ftver = a.Version;
```

Perhaps the `ftpath` variable is simply wrong. That results in 
> Warning: No properly formatted Contents.m file was found for 'xxx'

**Comment by schoffelen** [comment] 2020-03-10 10:02
@stephenwhitmarsh does this still require follow up? If so, the ball's in your court...

**Comment by stephenwhitmarsh** [comment] 2020-03-10 10:06
Hi JM,
I've stopped trying to use parpool, instead I am using Slurm. So, for now
it can be put under 'wont fix' I guess. On mobile, can change it later.
Cheers,
S

**Comment by schoffelen** [comment] 2020-03-10 10:08
Thanks Stephen, no worries. I'll close this one then.

**Closed by schoffelen** 2020-03-10 10:08 UTC
Labels: unconfirmed

**Comment by AljenU** [comment] 2022-08-11 13:36
I had a problem with using parfor within fieldtrip functions, that was similar to what is described here. The cause in that case was that the parallell pool had been started before the first call to ft_defaults (which adds all of fieldtrip to the matlab path, and makes it so ver() knows it). Whereas the matlab path at the moment the parpool is started, is the one that the workers know, which in that case does not include fieldtrip.
