### ISSUE TITLE
ft_denoisePCA fails using per-trial correction mode

### ISSUE THREAD

**Issue by awollbrink** [fieldtrip/fieldtrip#1365] opened 2020-03-31 17:06 UTC
the ft_denoisePCA function shows a faulty behavior when applying it to trial data and using the per-trial correction mode
using the following code snip with MEG data (273 channels in 'data' and 27 references in 'dataRef') the function returns different number of channels in 'dataCorr' and 'dataCorrPerTrial' depending on how cfg.pertrial was chosen ('no' -> 273 channels, 'yes' -> 27 channels)

I am using Fieldtrip revision 93dd0f61b on a Linux PC.

##### begin of code snip ########
%% denoise PCA
cfg=[];
cfg.channel={'MEG'};

cfg.pertrial= 'yes';
dataCorrPerTrial = ft_denoise_pca(cfg, data, dataRef);

cfg.pertrial= 'no';
dataCorr = ft_denoise_pca(cfg, data, dataRef);

**Comment by schoffelen** [comment] 2020-03-31 19:13
I cannot confirm this using the Subject01.ds data and the latest ft version on the github repo (master branch).

Please: 
1) verify if the problem persists using an up-to-date version of the code

If so:
2) provide a test function + data to reproduce your problem

**Comment by awollbrink** [comment] 2020-03-31 20:21
you can download test data from https://uni-muenster.sciebo.de/s/toh0edyZR046udJ
and use the following code

load('testDataDenoisePCA.mat', 'data', 'dataRef');

%% denoise PCA
cfg=[];
cfg.channel={'MEG'};

cfg.pertrial= 'yes';
dataCorrPerTrial = ft_denoise_pca(cfg, data, dataRef);

cfg.pertrial= 'no';
dataCorr = ft_denoise_pca(cfg, data, dataRef);

**Comment by schoffelen** [comment] 2020-04-01 07:11
Why do you input the reference data twice? 

The function is intended to work either
1. with a single data argument, containing both the channels-of-interest and the 'reference channels', then as specified as cfg.refchannel
2. with 2 data arguments, the first with the channels-of-interest and the second containing the reference channels.

Apparently, something goes allegedly (because you haven't reported back whether this persists in a more recent FT version) and silently wrong if the user by mistake includes a duplicate of the reference channels.

**Comment by schoffelen** [comment] 2020-04-01 07:31
Thanks for reporting this Andreas, I added a warning statement in the code (among others) to make users aware of the fact that the reference data was duplicated in the 2 data arguments, and made a small change that prevented fieldtrip to output the 'wrong' channels in that case.

**Closed by schoffelen** 2020-04-01 07:31 UTC
Labels: bug

**Comment by robertoostenveld** [comment] 2020-04-01 07:47
WIth the `ft_glmanalysis` that I am currently contemplating I have the same issue, i.e., one structure with data, another with model, or both data+model in one structure.

> The function is intended to work either
>
> 1. with a single data argument, containing both the channels-of-interest and the 'reference channels', then as specified as cfg.refchannel
> 2. with 2 data arguments, the first with the channels-of-interest and the second containing the reference channels.

I consider the redundancy in the interface undesirable. Why not always have a single data structure and specify which ref channels to use from it? That is not hard for the user, since `ft_appenddata` will do this. Perhaps we could change the function (for backward compatibility)  so that 

```
if ft_nargin>1
  ft_warning('please specify a single input argument');
  varargin = {ft_appenddata(tmp cfg, varargin{:})};
  ft_nargin = 1;
end
```

**Comment by awollbrink** [comment] 2020-04-01 07:57
Thanks Jan-Mathijs and Robert for the more detailed explanations.
The reason for parsing the second data structure just including reference channels was  that reference-channel specific preprocessing needed to be done (as written in the online help of the function)
I was not aware of that in case the first data includes ref channels those were used for the correction even the second data are provided
I therefore appreciate Roberts suggestion

**Comment by schoffelen** [comment] 2020-04-01 08:02
Andreas, just to be clear: in case 2 arguments are in the input, it's the data from the second argument that is to be used for the regression, for exactly the reason that you mention: you could have used different processing for the reference channels, as compared to the 'data' channels.

I was not aware of the existence of the ft_glmanalysis function.

I would be against enforcing a single input argument, because this would disallow advanced users to actually use channel sets with the same labels (but different processing having been applied to it, e.g. a lowpassfilter) to use as 'references'.

**Comment by schoffelen** [comment] 2020-04-01 08:08
So, I would favor (if potential redundancy in the input is undesired) to only allow to data input arguments, requiring the user to explicitly create (before calling the function) a data argument, and a refdata argument.

**Comment by awollbrink** [comment] 2020-04-01 08:09
I got that but just for clearance:
Am I right that in case of 2 data inputs the first should not contain any reference channels?

**Comment by schoffelen** [comment] 2020-04-01 08:17
Dear Andreas, the first can contain reference channels, but they will not be used.

In your use case their was a difference in the output between the pertrial and acrosstrials case due to an issue with respect the rolling back of the cfg argument in the recursive call to the function (in case of pertrial).

In another use case, where the 'reference channels' might be something more exotic, e.g. a set of true MEG channels, which have been processed to capture an artifact with known morphology, there might be an overlap between the names of the 'data channels' in the first argument and the names of the 'reference channels' to be taken from the second.

**Comment by awollbrink** [comment] 2020-04-01 08:25
thanks. Now (even) I got it!

**Comment by robertoostenveld** [comment] 2020-04-01 08:28
> In another use case, where the 'reference channels' might be something more exotic, e.g. a set of true MEG channels, which have been processed to capture an artifact with known morphology, there might be an overlap between the names of the 'data channels' in the first argument and the names of the 'reference channels' to be taken from the second.

agreed, that is a use case where appending would not work.
