### ISSUE TITLE
Why is the headmodel prepared again in ft_sourceanalysis function, line 344

### ISSUE THREAD

**Issue by VlastaKoudelka** [fieldtrip/fieldtrip#907] opened 2018-12-14 14:12 UTC
Dear Fieltrip,

thanks for the excellent job you do at first. I have been wondering quite a long time (and my students as well), why the headmodel is preperaded and aligned with sensors (in ft_sourceanalysis, line 344) even if I precomputed leadfield and passed to the ft_sourceanalysis funcion in cfg.grid. I have checked units, "elec" field in data, everything I thought it could cause this. I think, this realigment is not needed if I've already precomputed the leadfield. Maybe I am wrong. Thank you for your answer.

example:
cfg                   = [];
cfg.frequency         = freq_cmb.freq;
cfg.method            = 'dics';
cfg.keeptrials        = 'yes';
cfg.grid              = sourcemodel_lf;
cfg.headmodel         = vol;
cfg.keeptrials        = 'yes';
cfg.dics.lambda       = '5%';
cfg.dics.keepfilter   = 'yes';
cfg.dics.fixedori     = 'yes';
cfg.dics.realfilter   = 'yes';
source                = ft_sourceanalysis(cfg, freq_cmb);

command window:

Electrode 74 of 256
Scaling stiffnes matrix...
Preconditioning...
Finding startvector...
Solving equation system...

**Comment by simonhomoelle** [comment] 2018-12-14 14:54
Dear @VlastaKoudelka ,

yes this is a problem with the current code. However, there is a Pull request open #517  which should address this.

Cheers,
Simon

@robertoostenveld

**Comment by schoffelen** [comment] 2018-12-15 08:11
Thanks for the reminder Simon, I have merged the pull request. Looked good to me!

**Comment by robertoostenveld** [comment] 2018-12-15 09:01
Dear @VlastaKoudelka, this is mainly due to historic reasons. Could you please check again and let us know whether the latest version of the code makes more sense (in case of FEM). 

The same issue also applies to other methods for computing the forward model, so I think we also need a more generic solution.

**Comment by VlastaKoudelka** [comment] 2018-12-17 08:04
Thank you all for addressing this feature,

Robert, I will check the latest version, then. I will let you know.

Thanks,
Vlasta

**Comment by VlastaKoudelka** [comment] 2018-12-17 09:14
Dear all,

I've pulled the repo and double checked my paths in MATLAB. However, It seems the head/elec preprocessing is still recomputed. This happens also in case of pre-computed filter. Let me note, that both leadfield and filter were precomputed in the previous FT version. I would be happy to test more, if you had any suggestions or cases.

Thank you for your effort,
Vlasta

**Comment by VlastaKoudelka** [comment] 2018-12-18 08:16
I understand, this will take some time. I will let you know.

**Comment by VlastaKoudelka** [comment] 2019-01-07 15:06
Dear all,

I have pre-computed the leadfield based on the above mentioned testcase and it indeed works, see the console output below. Now, I have to review my script with the real data. I will compare it with the testcase, see attached. I will update you, were was the mistake.
Vlasta

the input is freq data with 42 channels, 1 frequencybins and no timebins
            label: {42x1 cell}
           dimord: 'rpttap_chan_freq'
             freq: 40.0391
    fourierspctrm: [1x42 double]
        cumsumcnt: 2000
        cumtapcnt: 1
              cfg: [1x1 struct]
             elec: [1x1 struct]

the call to "ft_selectdata" took 0 seconds
using electrodes specified in the data
creating dipole grid based on user specified dipole positions
using gradiometers specified in the configuration
160 dipoles inside, 21 dipoles outside brain
the call to "ft_prepare_sourcemodel" took 0 seconds
            label: {42x1 cell}
             freq: 40.0391
    fourierspctrm: [1x42 double]
        cumsumcnt: 2000
        cumtapcnt: 1
              cfg: [1x1 struct]
             elec: [1x1 struct]
           dimord: 'rpttap_chan_freq'

the call to "ft_selectdata" took 0 seconds
using precomputed leadfields
scanning grid
scanning grid 160/160

the call to "ft_sourceanalysis" took 1 seconds




[test_bug1820_issue907.zip](https://github.com/fieldtrip/fieldtrip/files/2733184/test_bug1820_issue907.zip)

**Comment by VlastaKoudelka** [comment] 2019-01-07 15:43
I've got it!
I checked what was stored in my already prepared leadfield structure, which came from previous pipeline:
                pos: [18000x3 double]
              xgrid: [1x24 double]
              ygrid: [1x30 double]
              zgrid: [1x25 double]
                dim: [24 30 25]
             inside: [18000x1 logical]
               unit: 'cm'
          leadfield: {1x18000 cell}
              label: {256x1 cell}
    leadfielddimord: '{pos}_chan_ori'
                cfg: [1x1 struct].
Since there were "xgrid, ygrid, and zgrid" and "dim" fields a new source model was created and for sure realigned, recomputed. That is my explanation.

Here is the appropriate structure:

                pos: [18000x3 double]
             inside: [18000x1 logical]
               unit: 'cm'
          leadfield: {1x18000 cell}
              label: {256x1 cell}
    leadfielddimord: '{pos}_chan_ori'
                cfg: [1x1 struct].

Thank you!

**Comment by VlastaKoudelka** [comment] 2019-01-10 13:53
Dear all,
just in case, I uploaded a reviewed test script, which also include ft_prepare_vol_sens procedure in advance to the leadfield calculation. I forgot to include it in my previous post. Thus, this file is appropriate and also works well. 
Thank you once again for your help.
Vlasta
[test_bug1820_issue907.zip](https://github.com/fieldtrip/fieldtrip/files/2745574/test_bug1820_issue907.zip)

**Comment by schoffelen** [comment] 2019-03-26 12:36
OK, I will quickly test your additions to the test script and incoporate them. Thanks for your constructive contributions.

**Closed by schoffelen** 2019-03-26 12:36 UTC

**Comment by vpiai** [comment] 2019-07-09 09:48
I was going to open an issue on something very similar until I encountered this. It is closed, so I was wondering what to do. I checked the history of changes to ft_sourceanalysis, ft_prepare_sourcemodel, and private/prepare_headmodel but I couldn't find any changes that would have resolved the particular issue I'm having, so I'll post it again. Hopefully you guys can tell me whether I should reopen the issue as I have not been able to make that decision myself :)

We are precomputing the leadfields outside of FT based on a FEM model for MEG data. The sourcemodel now contains what it should, to tell from Vlasta's comment from Jan 7th. We're using the most current version on the DCCN cluster.  (We refers to me, @mcpiastra @simonhomoelle )

```
pos: [42780×3 double]
unit: 'mm'
leadfield: {1×42780 cell}
leadfielddimord: '{pos}_chan_ori'
inside: [42780×1 logical]
label: {270×1 cell}
```
When calling ft_sourceanalysis with the following config (note the absence of the headmodel field):
```
cfgSF                     = [];
cfgSF.frequency           = 15;
cfgSF.method              = 'dics';
cfgSF.keepfilter          = 'yes';
cfgSF.dics.realfilter     = 'yes';
cfgSF.sourcemodel         = sourcemodel; %precomputed leadfields;
cfgSF.dics.keepfilter    = 'yes'; 
source_common           = ft_sourceanalysis(cfgSF, freq);
```
In line 354, it enters prepare_headmodel:
`[headmodel, sens, cfg] = prepare_headmodel(cfg, data);`

If I read 'sens' from the raw data and have an empty headmodel and pre-computed leadfields, I can run inverse/beamformer_dics and ft_sourceanalysis to completion, as I would expect. 
So it seems a matter of code flexibility; it should understand that it doesn't need to redo certain things. 

Any suggestions about how to go about? Should I reopen this issue, or am I missing some change in the code? (Sorry, I'm a newbie when it comes to code development!)

Thanks loads!

**Comment by schoffelen** [comment] 2019-07-09 10:02
Can you explicitly describe what's the issue now?

**Comment by vitpia** [comment] 2019-07-09 11:07
> In line 354, it enters prepare_headmodel:
[headmodel, sens, cfg] = prepare_headmodel(cfg, data);

Assuming a cfg with sourcemodel in the correct format; headmodel does not exist. 
Error when calling ft_sourceanalysis with cfg not containing headmodel: 
```
Reference to non-existent field 'headmodel'.

Error in prepare_headmodel (line 65)
if ischar(cfg.headmodel)

Error in ft_sourceanalysis (line 354)
[headmodel, sens, cfg] = prepare_headmodel(cfg, data);
```
If I give an empty headmodel, error (obviously):
```
Dot indexing is not supported for variables of this type.

Error in ft_convert_units (line 89)
if isequal(obj.unit, target)

Error in prepare_headmodel (line 91)
    headmodel  = ft_convert_units(headmodel,  cfg.sourcemodel.unit, 'feedback', true);

Error in ft_sourceanalysis (line 354)
[headmodel, sens, cfg] = prepare_headmodel(cfg, data);
```
I do know that the sourcemodel I'm passing on is sufficient/correct, because if I skip any of the lines in the pipeline that require a headmodel to be present, everything works. 
So I guess in sum, the issue is that ft_sourceanalysis still wants to compute the headmodel/sourcemodel anew, even though it's unnecessary because of my pre-computed leadfields. 
(Hopefully that's detailed enough?)
