### ISSUE TITLE
ft_qualitycheck error:  warning could not determine filetype

### ISSUE THREAD

**Issue by thehatingborg** [fieldtrip/fieldtrip#1193] opened 2019-08-15 22:11 UTC
I am trying to use **ft_qualitycheck** for my MEG data. However, it always gives me the warning saying it could not determine the file type of my subject.hist file. It further gives me, I think, an incomplete analysis picture.  ( I have a custom trial definition but also tried it without, not sure if this changes anything). Further I get the warning: Error updating legend not enough input arguments.

![ft_qualitycheck](https://user-images.githubusercontent.com/38266192/63129842-795d2a00-bf6d-11e9-9fe9-e8168b83c706.png)

**Comment by schoffelen** [comment] 2019-08-16 07:38
please be a bit more specific in your report.
It's not clear whether you get an error, or just warnings.
What is the operating system
what is the fieldtrip version
what is the matlab version
what is the MEG system

etc.

Also, perhaps it would be better to report this on the fieldtrip discussion list, so that other users might chime in. Once it is established that it is actually an issue, it can be documented here. Making it an issue right from the start causes it to only reach a limited amount of people, all of whom are very busy.

**Comment by schoffelen** [comment] 2019-08-21 12:19
@thehatingborg is there an update on this?

**Comment by thehatingborg** [comment] 2019-08-23 18:18
Not yet, currently trying the mailing list, thx for the suggestion.

**Comment by schoffelen** [comment] 2019-11-27 11:15
Any update on this? If it is not going to be pursued any further, I suggest to close this issue, unless it can indeed be confirmed

**Comment by thehatingborg** [comment] 2019-11-27 12:57
We didn't use the function anymore so it can be closed.

Thanks


Am Mittwoch, November 27, 2019 12:15 CET, Jan-Mathijs Schoffelen <notifications@github.com> schrieb:
 
Any update on this? If it is not going to be pursued any further, I suggest to close this issue, unless it can indeed be confirmed

**Comment by schoffelen** [comment] 2020-01-08 08:49
It's a pity that the issue reporter lost interest. Since this is still unconfirmed, I will close the issue for now.

**Closed by schoffelen** 2020-01-08 08:49 UTC
Labels: unconfirmed
