### ISSUE TITLE
ft_topoplotIC removes folder from path when trying to visualize ICA components

### ISSUE THREAD

**Issue by GiulioSev** [fieldtrip/fieldtrip#1216] opened 2019-09-10 15:47 UTC
Hi,

When trying to visualize the components after running ICA, I keep getting en error that certain functions (such as 'newline') are undefined. It appears that whenever I call ft_topoplotIC, the folder Matlablt2016b (containing these functions) is removed.

This is a short example of the code I'm using:

%% Info
% I am using Matlab 2016a on a Windows 10 system

%% Load the data
% It contains an EEG dataset from one participant,the accompanying cfg and
% the EEG layout.
% The data consists of 256 trials that have already been segmented
load('ExampleData.mat') 

%% Run ICA
% Perform independent component analysis
cfg        = [];
cfg.method = 'runica'; % this is the default and uses the implementation from EEGLAB
comp       = ft_componentanalysis(cfg, data_NoBigArt);

%% Identify artefacts
% Visualize the time course of the artefacts
cfg = [];
cfg.viewmode = 'component';
cfg.continuous = 'no'; % view the data in it's segments
cfg.channel = 'all'; % view all the component in one screen
cfg.layout = lay; % layout for DCC acticap
ft_databrowser(cfg,comp);

% Visualize the components
% This is were the error occurs, the error states that there is an
% undefined function 'newline' which is located in the Matlablt2016b
% folder. However, this folder is removed from the path before executing
% the function
figure
cfg = [];
cfg.component = 1:20;
cfg.layout    = lay'; % specify the layout file that should be used for plotting
cfg.comment   = 'no';
ft_topoplotIC(cfg, comp);

This is a link to the example data, let me know if it doesn't work.
https://drive.google.com/file/d/1XucYl15pEYhHbS7gc-t8jUzyH-iBDsTp/view?usp=sharing 

Best,
Giulio

**Comment by robertoostenveld** [comment] 2019-09-11 08:14
Thanks for the data and the script. Although I don't have easy access to windows, I am able to reproduce on R2016a on Linux.

When executing ft_databrowser, I notice the warning that it removes 'external/eeglab' from the path. 

>Warning: removing /home/mrphys/roboos/matlab/fieldtrip/external/eeglab toolbox from your MATLAB path 

That comes as a surprise to me, since data browser has nothing to do with eeglab. It can be traced back to 452f32fc. There I introduced a toolbox cleanup function, which I apparently only added for test purposes to ft_databrowser. So in this case ft_databrowser is cleaning up for ft_componentanalysis. That is not how it should be.

When executing ft_topoplotIC I see 

> Warning: removing "/home/mrphys/roboos/matlab/fieldtrip/compat/matlablt2016b" from your path, see http://bit.ly/2SPPjUS 

This relates to #899 and some other path setup issues. In this case I don't think there is anything wrong with the way that matlablt2016b was added to the path, i.e. `addpath(genpath(..))` was not used.  And it is clear that it should not be removed either.

I figured out that on 2016a the `newline` function (from compat/matlablt2016b) is removed since there is also another one 

> which newline -all
> /home/mrphys/roboos/matlab/fieldtrip/compat/matlablt2016b/newline.m
> /opt/matlab/R2016a/toolbox/shared/hdlshared/@hdl/newline.p           % hdl method

**Comment by robertoostenveld** [comment] 2019-09-11 08:16
I made the check for the incorrect adding of  compat/matlablt2016b to the path a little more strict, p-files and functions from specific classes (like `@hdl` in this case) don't count any more. 

I also removed the (still further to-be-tested) `ft_postamble hastoolbox` from ft_databrowser.

**Comment by robertoostenveld** [comment] 2019-09-11 08:20
We test all code every evening prior to releasing it, see [this link](http://www.fieldtriptoolbox.org/development/dashboard/). If all is well, the updated version will be released tonight and is available tomorrow.

**Closed by robertoostenveld** 2019-09-11 08:20 UTC
