### ISSUE TITLE
Issue with processing data with marker not falling on data samples

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2148] opened 2022-12-01 17:44 UTC
I have hacked Fieldtrip code extensively to avoid crashes, but even so, it still crashes. There are issues with ft_definetrial, ft_redefinetrial, and other epoch processing functions (ft_artifact_zvalue). Sometimes 99% of the epochs are fine but then others have different sizes (1 sample off) and create crashes down the line.

Upon reflection, instead of hacking the code, I think the best option is to force markers to fall on round samples at import time, and show a warning message to users.

Try the attached dataset from this BIDS release. I thought the ft_redefinetrial would crash for this dataset but it does not. It does for others. However the ft_artifact_zvalue function crashes.

https://nemar.org/dataexplorer/detail?dataset_id=ds002718

```matlab
clear 

cfg                         = [];
cfg.dataset                 = '/Users/arno/Downloads/sub-012_task-FaceRecognition_eeg.set';
cfg.hpfreq = 0.5;
cfg.hpfilter = 'yes';
data_clean = ft_preprocessing(cfg);

cfg                         = [];
cfg.dataset                 = '/Users/arno/Downloads/sub-012_task-FaceRecognition_eeg.set';
cfg.trialfun                = 'ft_trialfun_eeglabdemo'; % this is the default
cfg.trialdef.eventtype      = { 'trigger' 'stimulus' 5 17 'animal_target' 'animal_distractor' }; % the values of the stimulus trigger for the three conditions
cfg.trialdef.eventvalue     = { 'famous_new' 'scrambled_new' }; % the values of the stimulus trigger for the three conditions
cfg.trialdef.prestim        = 0.3; % in seconds
cfg.trialdef.poststim       = 0.7; % in seconds
cfg = ft_definetrial(cfg);
data2 = ft_redefinetrial(cfg, data_clean);

% Low-frequency data rejection
cfg = [];
cfg.artfctdef.zvalue.channel     = { 'EEG004' 'EEG002' 'EEG005' 'EEG007' 'EEG008' };
cfg.artfctdef.zvalue.cutoff      = 4;
cfg.artfctdef.zvalue.trlpadding  = 0;
cfg.artfctdef.zvalue.artpadding  = 0.1;
cfg.artfctdef.zvalue.fltpadding  = 0;
cfg.artfctdef.zvalue.bpfilter    = 'yes';
cfg.artfctdef.zvalue.bpfilttype  = 'but';
cfg.artfctdef.zvalue.bpfreq      = [0.5 2];
cfg.artfctdef.zvalue.bpfiltord   = 4;
cfg.artfctdef.zvalue.hilbert     = 'yes';
cfg.artfctdef.zvalue.interactive = 'no';
[~, artifact_EOG] = ft_artifact_zvalue(cfg, data2);
```

**Comment by arnodelorme** [comment] 2022-12-01 17:45
Data is here https://drive.google.com/drive/folders/1Vq5FvZkOLW5ffUWjujEjKXooOmNfn9ty?usp=sharing

**Comment by robertoostenveld** [comment] 2022-12-02 07:04
Can you shortly describe what you think is the cause of these crashes and where you had to make hacks to the code?

**Comment by robertoostenveld** [comment] 2022-12-02 07:05
is it due to markers beng read in seconds from the events.tsv file, and then not rounded off?

**Comment by arnodelorme** [comment] 2022-12-02 07:48
I do not think it is due to the sidecar file. I think it is due to the event definition in the file and the fact they are not rounded at import time.

**Comment by schoffelen** [comment] 2022-12-02 10:14
Wasn't this an issue that we recently discussed as well? i.e. the non-integer sample indices?

**Comment by arnodelorme** [comment] 2022-12-02 17:55
I also get this related error

```
reading the header from '../ds002680/sub-006/ses-1/eeg/sub-006_fieldtrip_temp.set'
reading the events from '../ds002680/sub-006/ses-1/eeg/sub-006_fieldtrip_temp.set'
found 1984 events
created 475 trials
the call to "ft_definetrial" took 2 seconds and required the additional allocation of an estimated 324 MB
the input is raw data with 31 channels and 1 trials
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Error using nan
Size inputs must be integers.

Error in ft_fetch_data (line 91)
dat = nan(numel(chanindx), endsample-begsample+1);

Error in ft_redefinetrial (line 283)
    data.trial{iTrl} = ft_fetch_data(dataold, 'header', hdr, 'begsample', begsample(iTrl), 'endsample', endsample(iTrl), 'chanindx', 1:hdr.nChans, 'skipcheckdata', 1);
```

using the attached script and data

https://drive.google.com/file/d/1CyXARYXMQY5BNPpa2xevp36pDNwxOndY/view?usp=share_link

**Comment by schoffelen** [comment] 2023-01-23 09:24
Hi @arnodelorme what is the status of this? I download the referenced data, but cannot reproduce the error you report for ft_artifact_zvalue (i.e. the case with sub-006), and also the test_fieldtrip script you sent along works for sub-012

**Comment by schoffelen** [comment] 2023-02-09 06:53
Closing for now, due to lack of follow up by @arnodelorme and I cannot reproduce the issue. Feel free to re-open if new information pops up.

**Closed by schoffelen** 2023-02-09 06:53 UTC
Labels: bug, unconfirmed
