### ISSUE TITLE
Results of source localisation obtained from different Fieldtrip releases differ

### ISSUE THREAD

**Issue by AlexandraSteina** [fieldtrip/fieldtrip#1587] opened 2020-11-09 07:47 UTC
**Describe the bug**

I performed source localisation on MEG-LFP data. The results of the source localisation differ when I use different Fieldtrip versions for the exact same data. The analysis pipeline and the sourceplots obtained from different fieldtrip releases is shown in the section below. The sourceplots obtained from fieldtrip-20190922 and fieldtrip-20200409 look the same. The sourceplot from fieldtrip-20200607 differs slightly from the others and the fieldtrip-20201009/fieldtrip-20201103 sourceplots look totally different. 

%%
I've checked whether the 'freq'-structure is the same for different fieldtrip releases and it is. 

%%
The output of 'ft_sourceanalysis' is different for these 5 different fieldtrip releases which can be seen in the sourceplots below. 

%%
I also noticed a difference when calculating the headmodel in particular when using  'ft_prepare_sourcemodel' . Comparing the "grid.pos" structure I noticed that the values obtained from the fieldtrip-20201009/fieldtrip-20201103 releases differ from the values obtained with fieldtrip-20190922, fieldtrip-20200409, fieldtrip-20200607. 
But I can't tell to which extend this difference influences the results because I have used 'ft_sourceanalysis' with the same data, same headmodel/sourcemodel with different fieldtrip releases and the results still differ as strongly as below. 

**To Reproduce**

Go to: https://github.com/AlexandraSteina/ft_sourceanalysis_problems.git and run the .m file with the instructions given in the .m file
   
**Expected behavior**
I would expect that the results are the same for all Fieldtrip versions because it is the exact same data that I've been using.

**Screenshots**
fieldtrip-20190922
![ft_2019](https://user-images.githubusercontent.com/74171284/98506765-8645f780-225c-11eb-9723-b993ab5ff3a4.png)

fieldtrip-20200409
![ft_april2020](https://user-images.githubusercontent.com/74171284/98506777-8d6d0580-225c-11eb-9731-7c2567e94d2b.png)

fieldtrip-20200607
![ft_june2020](https://user-images.githubusercontent.com/74171284/98506780-9067f600-225c-11eb-94ef-e5c4a418db5f.png)

fieldtrip-20201103
![ft_november2020](https://user-images.githubusercontent.com/74171284/98506784-9362e680-225c-11eb-8b5b-3ae2ab9edcad.png)

fieldtrip-20201009
![ft_october2020](https://user-images.githubusercontent.com/74171284/98506785-95c54080-225c-11eb-98f6-c38a1a6e6aa9.png)

**Environment and versions (please complete the following information):**
 - Operating System: [e.g. Linux]
 - MATLAB version [e.g. R2019b, type `ver`]
 - FieldTrip versions [fieldtrip-20190922, fieldtrip-20200409, fieldtrip-20200607, fieldtrip-20201009, fieldtrip-20201103]

**Additional context**

**Comment by schoffelen** [comment] 2020-11-12 21:07
OK, I think I am closing in. The attached picture shows the diagonal of the cross-spectrum, as used in beamformer_dics and ft_inverse_dics, respectively. Clearly the order of the channels is different. While it seems that the leadfields are the same in the two situations, the cause of the mismatch is very likely a channel order issue.

<img width="575" alt="Screenshot 2020-11-12 at 22 03 13" src="https://user-images.githubusercontent.com/1517611/98996584-63a13080-2533-11eb-945f-0163d8235938.png">

**Comment by schoffelen** [comment] 2020-11-12 21:07
To be continued

**Comment by schoffelen** [comment] 2020-11-13 07:50
OK, I found the culprit @AlexandraSteina and @robertoostenveld. It indeed happens to be a channel order thing, which occurs on line 594 of ft_sourceanalysis: 

tmpcfg.channel = setdiff(cfg.channel, cfg.refchan); % remove the refchan

setdiff leads to a potential reordering of the channels, which happened in Alexandra's case, due to the occasional occurrence of MEGabc3-MEGabc2 planar gradiometer pairs. Chaning this line into:

tmpcfg.channel = setdiff(cfg.channel, cfg.refchan); % remove the refchan

fixes the issue, and results in the 'desired' output.

This indeed is a potentially serious issue with the code (fortunately: DICS only it seems), which occurs if the order of the channels in the data is non-alphabetic.

@robertoostenveld I think we need to fix this, and ping the community about this.

Right now, I checked things with a local (on my home dir) set of unzipped fieldtrip versions. Should I write a test function that does a system unzip to /tmp in order to run this in a test function?

**Comment by robertoostenveld** [comment] 2020-11-13 09:11
Great that you got hold of the problem! Getting the channel order correct remains a challenge. 

You write that changing 

    tmpcfg.channel = setdiff(cfg.channel, cfg.refchan); % remove the refchan

into

   tmpcfg.channel = setdiff(cfg.channel, cfg.refchan); % remove the refchan

fixes the issue. However, those lines are identical, and still the same as https://github.com/fieldtrip/fieldtrip/blob/3a1ce015cdd661d4b280bace0958657c52c6f71d/ft_sourceanalysis.m#L594 

Should that not be like

```
>> setdiff({'a', 'c', 'b', 'd'}, 'a')
ans =
  1×3 cell array
    {'b'}    {'c'}    {'d'} 

>> setdiff({'a', 'c', 'b', 'd'}, 'a', 'stable')
ans =
  1×3 cell array
    {'c'}    {'b'}    {'d'}
```

**Comment by schoffelen** [comment] 2020-11-13 09:12
oops. copy-and-paste went wrong. I meant:

tmpcfg.channel(strcmp(cfg.channel, cfg.refchan)) = [];

**Comment by schoffelen** [comment] 2020-11-13 09:13
I am still confused by the 'stable'/'legacy' etc. bandaids that matlab introduced at some point

**Comment by schoffelen** [comment] 2020-11-13 18:55
pinging @britta-wstnr to put this on the radar

**Closed** 2020-11-25 12:55 UTC
Labels: bug
