### ISSUE TITLE
 ft_freqanalysis overestimates Nyquist, gives complex coefficient at Nyquist, doesn't give coefficient for 0 Hz

### ISSUE THREAD

**Issue by MatthiasGrabenhorst** [fieldtrip/fieldtrip#2265] opened 2023-06-28 21:01 UTC
We encountered some elementary problems in a time-frequency analysis at various frequencies, including 0 Hz and the Nyquist. The data has sampling frequency 600 Hz. We are using the latest fieltrip version, pulled from github on 26.06.2023.

1) Attempt 1 Using MTMFFT. We run the simplest version of MTMFFT 

cfg = [];
cfg.trials = [1:3];
cfg.method = 'mtmfft'; 
cfg.tapsmofrq = 1;
cfg.taper      = 'hanning';
cfg.keeptrials  = 'yes';   
cfg.output      = 'fourier';

fourcoefsFFT = ft_freqanalysis(cfg,data1);

We got real valued coefficients for 0Hz.
But very suprisingly the highest frequency we got was 

fourcoefsFFT.freq(end)
300.6237 

which is higher than the Nyquist. How is this possible?

Then we tried using the 
cfg.foi = [0:300];
cfg.pad = 10;

and set the frequencies so that we can control the resolution of the output frequencies and although the last frequency in the results was exactly the Nyquist, 300 (checked with long g resolution in matlab), its coefficient was complex.

2) Attempt 2 using MTMCONVOL

cfg = [];
cfg.trials = [1:3];
cfg.method = 'mtmconvol'; 
cfg.foi = [0:300]; 
cfg.toi = -0.2; 
cfg.t_ftimwin = min(5*(1./cfg.foi),0.4);      % for each foi, this sets the entries with 5 cycles larger than 0.4 to 0.4
cfg.taper      = 'hanning';
cfg.keeptrials  = 'yes';   
cfg.output      = 'fourier';

fourcoefs = ft_freqanalysis(cfg,data); 

Now in the output there is no coefficient for 0 Hz at all.
Also the last frequency of the output is again 300.6237 Hz, higher than the Nyquist.

Then we used again 
cfg.pad = 10;

to control the resolution of the output frequencies.

Again frequency 0 Hz is missing.
And although in the output the last frequency is exactly the Nyquist, 300 Hz, its coefficient is again complex.

Greetings!

Matthias and Georgios

**Comment by schoffelen** [comment] 2023-06-29 07:15
Thanks for filing it here @MatthiasGrabenhorst! Please feel free to also ping Georgios here.

I started to look into this issue, and I can confirm your observations.

The first part of your issue 1 is mostly explained by this FAQ:
https://www.fieldtriptoolbox.org/faq/why_does_my_output.freq_not_match_my_cfg.foi_when_using_mtmfft_in_ft_freqanalyis/ 

The fact that the highest frequency bin goes beyond Nyquist is probably a rounding issue. We may consider to build in a check so that FT only returns the frequency bins <= Nyquist.

I could reproduce the fact that the cfg.pad in your case resulted in an integer frequency axis, but in a complex valued Nyquist frequency bin. The culprit in this case is the line https://github.com/fieldtrip/fieldtrip/blob/d63e54366d6ae83d257173a2ec1c0688b0ee1ffd/specest/ft_specest_mtmfft.m#L101C1-L101C12 which leads to a 'wrong' value of postpad, due to numerical precision issues. As a consequence, the padded length is not 6000 samples long, but 6001, which causes the frequency axis to be not exactly sampled as expected. For some reason, the freq.freq that is returned is properly rounded, but mismatches the exact frequency bins of the data. 

The ceil() operation is to blame here, and I think that this can be safely replaced by a round(), or the line that computes the postpad can read: postpad = round(pad*fsample) - ndatsample;

% some code to exemplify the issue:

ndatsample = [101:591]; % explore a range of values to explore that the problem comes and goes, depending on the exact number of samples
pad = 10;
fsample = 600;
dattime = ndatsample / fsample; % total time in seconds of input data

postpad1    = ceil((pad - dattime) * fsample);
postpad2   = round((pad - dattime) * fsample);

% expected value of postpad
postpad = 6000 - ndatsample;

assert(all(postpad2==postpad), 'rounding does not work');
assert(all(postpad1==postpad), 'ceiling does not work');

@robertoostenveld what do you think, can we update ft_specest_mtmfft silently, to increase numeric precision and thus more smooth alignment with the user expectations or should this be escalated a bit more?

**Comment by schoffelen** [comment] 2023-07-02 18:16
I fixed the rounding inaccuracy, so that the mtmfft method now properly returns a numerically strictly real valued Nyquist frequency bin.

By construction ft_specest_mtmconvol ditches the DC bin, since it cannot create a wavelet for it. (although theoretically it might create a all-ones for the cosine part, and an all-zeros for the sine part I guess). ft_specest_mtmconvol also has a complicated way of dealing with the phase, i.e. it rotates the phase such that the phase at the toi centered at time point 0 is 0 (as far as I understand the code, and its comments). I haven't checked this myself, but one needs to make choices what to spend time on occasionally...

Let me know, if my changes to ft_specest_mtmfft works well enough for your purposes.

**Comment by schoffelen** [comment] 2023-07-04 07:39
@MatthiasGrabenhorst can this be closed, and the corresponding pull request merged?

**Comment by schoffelen** [comment] 2023-08-08 07:11
@MatthiasGrabenhorst I would like to move forward with this (i.e. close the issue and merge the PR). The ball is in your court so feel free to take action.

**Comment by MatthiasGrabenhorst** [comment] 2023-08-08 09:15
Hi JM,

Yes, please close the issue.

Best,

Matthias



Von: Jan-Mathijs Schoffelen ***@***.***>
Antworten an: fieldtrip/fieldtrip ***@***.***>
Datum: Dienstag, 8. August 2023 um 09:11
An: fieldtrip/fieldtrip ***@***.***>
Cc: "Grabenhorst, Matthias" ***@***.***>, Mention ***@***.***>
Betreff: [EXT]:Re: [fieldtrip/fieldtrip] ft_freqanalysis overestimates Nyquist, gives complex coefficient at Nyquist, doesn't give coefficient for 0 Hz (Issue #2265)

ATTENTION: EXTERNAL EMAIL. Do NOT click on links or attachments unless you trust the sender of this message.
________________________________

@MatthiasGrabenhorst<https://github.com/MatthiasGrabenhorst> I would like to move forward with this (i.e. close the issue and merge the PR). The ball is in your court so feel free to take action.

**Closed** 2023-08-08 15:10 UTC
Labels: bug
