### ISSUE TITLE
structure sensor 3D Scan Data - texture size error

### ISSUE THREAD

**Issue by ssanchezalonso** [fieldtrip/fieldtrip#1825] opened 2021-07-06 19:40 UTC
I am trying to localize NIRS optodes using a 3D structure sensor (specifically Structure Sensor Mark II, https://structure.io/structure-sensor). I have been following the FieldTrip scanner tutorial, which seems to work with most of my scans (20 scans in total), but not for a subset (7 scans). When I try to load the data for this subset of scans, I get an error in the refine function:
 
Error using refine (line 72)
invalid size of texture
 
Error in ft_read_headshape (line 1030)
        [shape.pos, shape.tri, texture] = refine(shape.pos, shape.tri,...
 
 
Searching through the discussion list, I saw that someone run into a similar error about a year ago, which was caused by the assumptions that FieldTrip makes about the content of the obj-file. It seems that this issue had been solved, so I wonder whether this is due to a similar or new issue.
 
I am using fieldtrip-20210629 and jpg as image file.

**Comment by robertoostenveld** [comment] 2021-07-07 07:24
I recall the previous time we encountered this the error being due to a corrupt file on disk. Or more precisely, one of the three (obj/mtl/jpg) files being corrupt. That was due to incomplete 3D rendering on the iPad, i.e. the proper procedure is to scan, 3d color render (which takes some 10 seconds or so), visually inspect, and then use the email program on the iPad to transfer the data. If the rendering was not done, the Model.zip email attachment (containing the obj/mtl/jpg triplet) would be corrupt.

An alternative problematic use case that I can imagine is that the files are renamed. Inside the `mtl` file (which is a text file) there is a reference to `Model.jpg`. If the three files are renamed without updating that reference, the error is that `Model.jpg` cannot be read. 

Both cases are sufficiently likely to happen that we might want to make the code more robust, or if that is not possible to print more informative error messages.

**Comment by robertoostenveld** [comment] 2021-07-07 07:25
@schoffelen did you receive the data? Can you put it on `/home/common`?

**Comment by schoffelen** [comment] 2021-07-07 07:41
I think that this time it is not a corrupt file issue. I pulled the stuff locally (will upload soon), and the cause here is the fact that occasionally some vertices are not assigned to a triangle (don't ask me why). The part of the code that deals with this in ft_read_headshape (i.e. the call to remove_vertices) should also include the removal of the corresponding texture-line (provided the number of texture lines is equal to the number of vertices to begin with). I will PR a fix, and upload the the models to the filesystem. Do we have some other examples of (previously working) models so that I can test whether the change does not break anything?

**Comment by schoffelen** [comment] 2021-07-07 09:00
hi @ssanchezalonso would it be possible for you to also upload into the Dropbox folder that you shared with me an example of a Model that did not give any problems?

**Comment by ssanchezalonso** [comment] 2021-07-07 14:47
Hi Jan-Mathjijs,

Thank you for this email and explanation of the issue. I have uploaded to the Dropbox folder two examples of Models that did not give any problems.

Sara



From: Jan-Mathijs Schoffelen ***@***.***>
Reply-To: fieldtrip/fieldtrip ***@***.***>
Date: Wednesday, July 7, 2021 at 5:00 AM
To: fieldtrip/fieldtrip ***@***.***>
Cc: "Sanchez-alonso, Sara" ***@***.***>, Mention ***@***.***>
Subject: Re: [fieldtrip/fieldtrip] structure sensor 3D Scan Data - texture size error (#1825)


hi @ssanchezalonso<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fssanchezalonso&data=04%7C01%7Csara.sanchez.alonso%40yale.edu%7C9a3c2f8d05c64a70cf6008d94125b21a%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637612452420660849%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xnLZQPJSH24m4%2BnBpieuQ3I88BNMEZnUa2k9wXgkvtk%3D&reserved=0> would it be possible for you to also upload into the Dropbox folder that you shared with me an example of a Model that did not give any problems?

**Closed** 2021-07-08 15:10 UTC
Labels: question
