### ISSUE TITLE
function nearest() is different in newer version of matlab (2024a), ft functions are not working correctly anymore

### ISSUE THREAD

**Issue by alinatet** [fieldtrip/fieldtrip#2434] opened 2024-07-18 06:17 UTC
The function nearest() is different in a newer version of Matlab (2024a). Now it has only one input and makes a rounding.

This is how a new nearest() function looks like in Matlab 2024:
function y = nearest(x)
%NEAREST Round to nearest integer - ties round up
%   NEAREST(X) rounds the elements of X to the nearest integer, and
%   ties are rounded up (towards +inf).
%
%   CONVERGENT, NEAREST, and ROUND only differ in the way they treat
%   values whose fractional part is 0.5.
%
%   In CONVERGENT, the ties are rounded to the nearest even integer. 
%   In NEAREST, the ties are rounded up.
%   In ROUND, the ties are rounded up if positive, and down if negative.
%
%   Example:
%
%       x=(-3.5:3.5)';
%       [x convergent(x) nearest(x) round(x)]
%
%   See also FLOOR, CEIL, CONVERGENT, FIX, ROUND

%   Thomas A. Bryan
%   Copyright 1999-2007 The MathWorks, Inc.

if isinteger(x)
    y = x;
elseif isreal(x)
    y = floor(x+0.5);
else
    y = floor(x+(0.5+0.5i));
end

**Comment by robertoostenveld** [comment] 2024-07-18 10:03
Hi Alina,

The function you refer to seems to be https://nl.mathworks.com/help/fixedpoint/ref/nearest.html
whereas fieldtrip includes a function with the same name that lives here https://github.com/fieldtrip/fieldtrip/blob/master/utilities/nearest.m

I don't have the fixed point toolbox, which probably explains that - although fixedpoint/nearest function already exists since 2008 - I never encounter this clash between the two functions with the same name.

Can you type `which nearest`? I don't understand why the fieldtrip version would not be higher on the path and hence found first.

best
Robert

**Comment by schoffelen** [comment] 2024-08-28 23:43
hi @alinatet, what is the status of this? So far we haven't been able to reproduce it, and in the absence of new information from your side I think we will close this issue soon.

**Closed** 2024-11-05 13:21 UTC
Labels: question
