### ISSUE TITLE
dimord creation in ft_statistics_mvpa

### ISSUE THREAD

**Issue by juliankeil** [fieldtrip/fieldtrip#2107] opened 2022-09-15 14:12 UTC
**Describe the bug**
In "ft_statistics_mvpa", in line 372, the "dimord" is created from the "result"-field of the MVPA-Light output. If one requests more than one performance metric (e.g., {'accuracy','tval'}), "result" contains 2 lines of cell-array outputs. As a consequence, the line dimord = strrep(result.perf_dimension_names, ' ', ''); fails.
To solve this, explicitly state the line of the cell-array to use. Since the dimensions should always be the same, using the first line should always work:
dimord = strrep(result.perf_dimension_names{1}, ' ', '');

**To Reproduce**
1. Go to 'https://www.fieldtriptoolbox.org/tutorial/mvpa_light/'
2. Use the example "Search across both time and channels"
cfg = [] ;  
cfg.method        = 'mvpa';
cfg.latency       = [-0.1, 0.8];
cfg.features      = [];
cfg.mvpa.repeat   = 2;
cfg.design        = [ones(nFIC,1); 2*ones(nFC,1)];

4. Add cfg.mvpa.metric   = {'accuracy','tval'}; 
5. Run the example: stat = ft_timelockstatistics(cfg, dataFIC_LP, dataFC_LP)
6. See error: Error using strrep
Cell elements must be character vectors.

Error in ft_statistics_mvpa (line 372)
  dimord = strrep(result.perf_dimension_names, ' ', '');

Error in ft_timelockstatistics (line 185)
  [stat, cfg] = statmethod(cfg, dat, design);

**Expected behavior**
"dimord" should contain the dimension information, in this case "chan_time".

**Screenshots**
Not applicable

**Environment and versions (please complete the following information):**
 - Operating System: Mac OSX 10.15.7
 - MATLAB version R2017b
 - FieldTrip version revision cc6c44ddb.

**Additional context**

**Comment by schoffelen** [comment] 2022-09-15 14:14
Hi @juliankeil thanks for the detailed report. We'll look into it. And good to see that people seem to find the (intended) supported functionality/gateway to mvpa-light useful...

**Comment by schoffelen** [comment] 2022-09-15 14:17
matlab 2017b, does that still run :) ?

**Comment by schoffelen** [comment] 2022-09-16 07:52
OK, confirmed. I'll make a fix in a PR, which will be in the master branch of the repo soon, and once the daily tests have passed it will also show up in the release branch

**Closed** 2022-09-16 07:55 UTC
Labels: bug
