### ISSUE TITLE
Using matrix for cfg.graphcolor in ft_singleplotER (and ft_multiplotER)

### ISSUE THREAD

**Issue by johalgermissen** [fieldtrip/fieldtrip#1214] opened 2019-09-06 16:19 UTC
The documentation of ft_singleplotER says for cfg.graphcolor:
` alternatively, colors can be specified as nx3 matrix of rgb values'.`

Using something like `cfg.graphcolor =  [0 .5 0; 0.8 0 0] ` throws an error:

```
Error using plot
Color value must be a 3 element vector

Error in ft_plot_vector (line 405)
        h = plot(hdat, vdat(i,:), style, 'LineWidth', linewidth, 'Color', color(i,:), 'markersize', markersize,
        'markerfacecolor', markerfacecolor);

Error in ft_singleplotER (line 440)
    ft_plot_vector(xval, yval(i,:), 'style', cfg.linestyle{i}, 'color', graphcolor(i), 'highlight', mask,
    'highlightstyle', cfg.maskstyle, 'linewidth', cfg.linewidth, 'hlim', [xmin xmax], 'vlim', [ymin ymax],
    'facealpha', cfg.maskfacealpha);
```

I think currently, when calling ft_plot_vector in lines 436 and 440 and specifying `graphcolor(i)`, that only works if graphcolor is a character array, but not if it is a matrix (where it retrieves only a single element and not an entire row, which would need `graphcolor(i,:)`.

My idea would be an additional case distinction for the call to ft_plot_vector of whether graphcolor is a character array or numeric. But maybe there is a more elegant solution?

Same applies to ft_multiplotER I guess.

**Comment by robertoostenveld** [comment] 2019-09-18 09:06
The following code reproduces the problem
```
timelock1 = ft_timelockanalysis([], ft_freqsimulation([]));

cfg = [];
cfg.parameter = 'avg';
cfg.operation = '-1*x1';
timelock2 = ft_math(cfg, timelock1);

cfg = [];
cfg.channel = 'mix';
ft_singleplotER(cfg, timelock1, timelock2);

cfg = [];
cfg.channel = 'mix';
cfg.graphcolor = 'gy';
ft_singleplotER(cfg, timelock1, timelock2);

cfg = [];
cfg.channel = 'mix';
cfg.graphcolor = [
  1 0 0
  0 1 0
  ];
ft_singleplotER(cfg, timelock1, timelock2);

```

**Comment by robertoostenveld** [comment] 2019-09-18 09:13
It seems to be enough to ensure that graphcolor is Nx1 or Nx3 and then always select a whole row. In the case of a Nx1 char array, that will pass a letter to ft_plot_vector. In the case of a numeric Nx3 it will pass the RGB triplet.

**Comment by robertoostenveld** [comment] 2019-09-18 09:15
if all is well - i.e. all tests passing - the fix will be included in the release (and on home/common) tomorrow.

**Closed by robertoostenveld** 2019-09-18 09:15 UTC
